#!/bin/zsh

# Generate ~/.config/herdr/config.toml from the shared config (and this
# machine's config.local.toml, if any), keeping aside a file not generated here.
mkdir -p ~/.config/herdr
conf=~/.config/herdr/config.toml
[ -f "$conf" ] && [ ! -L "$conf" ] && ! head -n 1 "$conf" | grep -q '^# Generated by' &&
  mv "$conf" "$conf.bak"

# Without python 3.11 there is no merge; the shared file alone is still a config.
if ! zsh ~/.dotfiles/shell/_tools/herdr/build-config.sh; then
  echo "herdr: linking the shared config instead, config.local.toml is not applied" >&2
  ln -sfn ~/.dotfiles/shell/_tools/herdr/config.toml "$conf"
fi
