#!/usr/bin/env python3
"""Build the config.toml herdr actually runs on.

herdr reads exactly one config file and TOML has no include, so the shared
config in the dotfiles and a machine's own overrides have to be merged into a
third file: ~/.config/herdr/config.toml itself, written by build-config.sh, and
inside tmux config.effective.toml, which the herdr() wrapper in shell/dj.sh
hands the client through HERDR_CONFIG_PATH.

    merge-config.py OUT BASE [LOCAL] [--prefix KEY]

Tables merge key by key, and LOCAL wins wherever both set the same key; any
other value (strings, arrays, arrays of tables) is replaced whole. --prefix
overrides keys.prefix after the merge, for running inside tmux.

Needs tomllib (Python 3.11+). Exits non-zero without touching OUT if it is
missing or either file does not parse, so the caller can keep the config it has.
"""

import json
import sys

try:
    import tomllib
except ImportError:
    sys.exit("herdr: python 3.11+ needed to merge config.local.toml")


def merge(base, over):
    out = dict(base)
    for key, value in over.items():
        if isinstance(value, dict) and isinstance(out.get(key), dict):
            out[key] = merge(out[key], value)
        else:
            out[key] = value
    return out


def is_table_array(value):
    return isinstance(value, list) and value and all(isinstance(v, dict) for v in value)


def key(name):
    return name if name.replace("_", "").replace("-", "").isalnum() else json.dumps(name)


def scalar(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        # A JSON string is a valid TOML basic string.
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, list):
        return "[" + ", ".join(scalar(v) for v in value) + "]"
    if isinstance(value, dict):
        return "{ " + ", ".join(f"{key(k)} = {scalar(v)}" for k, v in value.items()) + " }"
    raise TypeError(f"herdr: cannot write {type(value).__name__} values")


def emit(table, path, lines):
    # Plain keys first: in TOML they belong to the most recent header, so they
    # have to come before any sub-table opens.
    for k, v in table.items():
        if not isinstance(v, dict) and not is_table_array(v):
            lines.append(f"{key(k)} = {scalar(v)}")
    for k, v in table.items():
        sub = path + [key(k)]
        if isinstance(v, dict):
            lines += ["", f"[{'.'.join(sub)}]"]
            emit(v, sub, lines)
        elif is_table_array(v):
            for item in v:
                lines += ["", f"[[{'.'.join(sub)}]]"]
                emit(item, sub, lines)


def main(argv):
    prefix = None
    if "--prefix" in argv:
        i = argv.index("--prefix")
        prefix = argv[i + 1]
        del argv[i:i + 2]

    out_path, *sources = argv
    config = {}
    for path in sources:
        try:
            with open(path, "rb") as f:
                config = merge(config, tomllib.load(f))
        except (OSError, tomllib.TOMLDecodeError) as e:
            sys.exit(f"herdr: {path}: {e}")

    if prefix:
        config.setdefault("keys", {})["prefix"] = prefix

    lines = [
        "# Generated by ~/.dotfiles/shell/_tools/herdr/merge-config.py -- do not edit.",
        "# Sources: " + ", ".join(sources) + (f" (prefix {prefix})" if prefix else ""),
        "",
    ]
    emit(config, [], lines)
    with open(out_path, "w") as f:
        f.write("\n".join(lines).strip() + "\n")


if __name__ == "__main__":
    main(sys.argv[1:])
